AllCops:
  Exclude:
    - '**/metadata.rb'
    - '**/*.gemspec'
    - '**/version.rb'
    - '*file'

Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 9

Metrics/LineLength:
  Max: 180
Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Enabled: false
